accounts/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import CreateView, TemplateView

from .models import CustomUser
from .forms import UserCreationForm
from .views import RegisterCreateView, UserLoginView, UserLogoutView

urlpatterns = [
    path('', TemplateView.as_view(template_name = 'accounts/index.html'), name='index'),
    path('register/', RegisterCreateView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login' ),
    path('logout/', UserLogoutView.as_view(), name='logout')
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.home, name='index'),
    path('create/', views.create_post, name='create'),
    path('update/<slug:slug>/', views.update_post, name='update'),
    path('delete/<slug:slug>/', views.delete_post, name='delete'),
    path('post/<slug:slug>', views.post, name='post')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'), namespace='home')),
    path('accounts/', include(('accounts.urls','accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('marketplace/', include(('marketplace.urls','marketplace'), namespace='marketplace')),
    path('expenses/', include(('expenses.urls', 'expenses'), namespace='expenses'))
    #path('movies', include(('movies.urls','movies'), namespace='movies'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = TemplateView.as_view(template_name="404.html")

home/models.py
from django.db import models
from django.template.defaultfilters import slugify

class Tag(models.Model):
    name = models.CharField(max_length=200)


    def __str__(self):
        return self.name


class Post(models.Model):
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to='home/', default='blank/blank.jpg')
    body = models.TextField(null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, null=True, blank=True)
    active = models.BooleanField(default=True)
    slug = models.SlugField(unique=True, null=True, blank=True)


    # Saving unique slug    
    def save(self, *args, **kwargs):
        if self.slug == None:
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 0
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()
                            
            self.slug = slug

        super().save(*args, **kwargs)


    def __str__(self):
        return self.headline
    

home/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('slug',)

home/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.contrib.admin.views.decorators import staff_member_required

from .models import Post
from .forms import PostForm

def home(request):
    return render(request, 'home/index.html',{'posts': Post.objects.all()})

def post(request, slug):
    return render(request, 'home/post.html', {'post': Post.objects.get(slug=slug)})

# CRUD VIEWS
@staff_member_required
def create_post(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid:
            form.save()
        return redirect('home:index')
    else:
        context = {'form': form}
        return render(request, 'home/create_post.html', context)
    

@staff_member_required 
def update_post(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid:
            form.save()
        return redirect('home:index')
    else:
        context = {'form': form,
                   'post': post}
        return render(request, 'home/update_post.html', context)
    
@staff_member_required
def delete_post(request, slug):
    post = Post.objects.get(slug=slug)
    
    if request.method == 'POST':
        post.delete()
        return redirect('home:index')
    else:
        context = {'post': post}
        return render(request, 'home/delete.html', context)

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand d-flex p-2"  href="{% url 'home:index' %}">Home</a>
        <div class="collapse navbar-collapse d-flex flex-row-reverse" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:create' %}">Create Post</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}?next={{request.path}}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}?next={{request.path}}">Login</a>
                    </li>
                {% endif %}                    
              </ul>
        </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

home/templates/home/create_post.html
{% extends "home/base.html" %}

{% block title %}
    Create Post
{% endblock %}

{% block content %}
<form action="{% url 'home:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
</form>
{% endblock %} 

home/templates/home/delete.html
{% extends "home/base.html" %}

{% block title %}
    Delete {{ post.headline }}
{% endblock %}

{% block content %}
<div style="text-align: center;">
    <h4 style="margin-top: 5%;">Are you sure You want to remove {{ post.headline }}?</h4>  
    <form method="post">
        {% csrf_token %}
        <button>Delete</button>
        <button type="button"><a href="{% url 'home:index' %}" style="text-decoration:none; color: black;">Back</a></button>
    </form>
</div>
{% endblock %} 

home/templates/home/index.html
{% extends "home/base.html" %}

{% block title %}
    Krzysztof Lesiak
{% endblock %}

{% block content %}
<div style="text-align: center;">
    <h1>Apps:</h1>
    {% for post in posts %}
        <a href="{{ post.headline|lower }}">{{ post.headline }}</a> 
        {% if user.is_staff %}
            | <a href="{% url 'home:update' post.slug %}">Update</a> |
            <a href="{% url 'home:delete' post.slug %}">Delete</a>
        {% endif %}<br>  
    {% endfor %}
    
</div>
{% endblock %} 

home/templates/home/post.html
{% extends "home/base.html" %}

{% block title %}
    {{ post.headline }}
{% endblock %}

{% block content %}
<div style="text-align: center;">
    {{ post.headline }}    
</div>
{% endblock %} 

home/templates/home/update_post.html
{% extends "home/base.html" %}

{% block title %}
    Update {{ post.headline }}
{% endblock %}

{% block content %}
<form action="{% url 'home:update' post.slug %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
</form>
{% endblock %} 