accounts/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import CreateView, TemplateView

from .models import CustomUser
from .forms import UserCreationForm
from .views import RegisterCreateView, UserLoginView, UserLogoutView

urlpatterns = [
    path('', TemplateView.as_view(template_name = 'accounts/index.html'), name='index'),
    path('register/', RegisterCreateView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login' ),
    path('logout/', UserLogoutView.as_view(), name='logout')
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.home, name='index'),
    path('create/', views.create_post, name='create'),
    path('update/<slug:slug>/', views.update_post, name='update'),
    path('delete/<slug:slug>/', views.delete_post, name='delete'),
    path('post/<slug:slug>', views.post, name='post')
]

marketplace/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (AuctionCreateView, MarketplaceListView, AuctionDetailView, CategoryListView,
                    WatchlistView, MyAuctionsListView, MyAuctionUpdateView, MyAuctionDeleteView)

urlpatterns = [
     path('',
         MarketplaceListView.as_view(),
         name='index' ),
     path('create/',
         AuctionCreateView.as_view(),
         name='create'),
     path('auction/<str:pk>/<slug:slug>', AuctionDetailView.as_view(), name='auction'),
     path('category/<str:category>/', CategoryListView.as_view(), name='category'),
     path('watchlist/', WatchlistView.as_view(), name='watchlist'),
     path('my_auctions/', MyAuctionsListView.as_view(), name='my_auctions'),
     path('update/<int:pk>/', MyAuctionUpdateView.as_view(), name='update'),
     path('delete/<int:pk>',MyAuctionDeleteView.as_view(),name='delete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'), namespace='home')),
    path('accounts/', include(('accounts.urls','accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('marketplace/', include(('marketplace.urls','marketplace'), namespace='marketplace')),
    path('expenses/', include(('expenses.urls', 'expenses'), namespace='expenses'))
    #path('movies', include(('movies.urls','movies'), namespace='movies'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = TemplateView.as_view(template_name="404.html")

marketplace/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify

import datetime

class Category(models.Model):
    class Meta:
        ordering = ('-pk',)

    name = models.CharField(max_length=50, unique=True, default='Other')

    def __str__(self):
        return f'{self.name}'


class Auction(models.Model):

    class Meta:
        ordering = ('-date', '-pk')
        
    
    name = models.CharField(max_length=64)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=16, decimal_places=2)
    description = models.TextField(max_length=2000, blank=True)
    photo = models.ImageField(upload_to='marketplace/', blank=True, default='blank/blank.jpg')
    created_by = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today, db_index=True)
    slug = models.SlugField(max_length=200)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Auction, self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('marketplace:auction', args=[str(self.pk), str(self.slug)])


    def __str__(self):
        return f'{self.name}-{self.pk}'

marketplace/forms.py
from django import forms

from .models import Auction, Category

import datetime

this_year = datetime.date.today().year

class AuctionForm(forms.ModelForm):
    
    category = forms.ModelChoiceField(queryset=Category.objects.all(),
                                      initial=Category.objects.get(name = 'Other'),
                                      empty_label=None,
                                      required = False)

    class Meta:
        model = Auction
        fields = ['name', 'category', 'price', 'photo', 'description']


class AuctionFilterForm(forms.ModelForm):
    name = forms.CharField(required=False,
                           label='',
                           widget=forms.TextInput(
                                attrs={'placeholder': 'Name'})
                            )

    date_from = forms.DateField(label='From mm/dd/yy:',
                                required=False,
                                widget=forms.SelectDateWidget(
                                    years = range(this_year, this_year - 10, -1))
                                )

    date_to = forms.DateField(label='To mm/dd/yy:',
                              required=False,
                              widget=forms.SelectDateWidget(
                                years = range(this_year, this_year - 10, -1))
                              )

    price_from = forms.DecimalField(decimal_places=2,
                                    required=False,
                                    label='',
                                    widget=forms.NumberInput(
                                        attrs={'placeholder': 'Price From'})
                                    ) 

    price_to = forms.DecimalField(decimal_places=2,
                                    required=False,
                                    label='',
                                    widget=forms.NumberInput(
                                        attrs={'placeholder': 'Price To'})
                                    ) 

    price_sort = forms.ChoiceField(choices=(('', ''), ('ASC', 'Ascending'), ('DESC', 'Descending')),
                                  required=False,
                                  label='Sort by price:'
                                  )                             


    class Meta:
        model = Auction
        fields = ('name', 'date_from', 'date_to', 'price_from', 'price_to', 'price_sort')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)     

marketplace/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DetailView, View, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Auction, Category 
from .forms import AuctionForm, AuctionFilterForm
from . import utils

from accounts.models import CustomUser


class AuctionCreateView(LoginRequiredMixin  ,CreateView):
    model = Auction
    form_class = AuctionForm
    template_name = 'marketplace/create.html'
    success_url = reverse_lazy('marketplace:index')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class MarketplaceListView(ListView):
    model = Auction
    paginate_by = 5
    template_name = 'marketplace/index.html'
    context_object_name = 'auctions'
    
    def get_context_data(self, object_list = None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list

        q = self.request.GET.get('q')
        if q:
            queryset = queryset.filter(name__icontains = q)

        form = AuctionFilterForm(self.request.GET)
        queryset = utils.filter_form(form, queryset)

        return super().get_context_data(**kwargs,
                    categories = Category.objects.all(),
                    object_list = queryset,
                    form=form
                    )


class AuctionDetailView(DetailView):
    model = Auction
    template_name = 'marketplace/auction.html'
    context_object_name = 'auction'

    # Display Auction details
    def get_context_data(self, **kwargs):
        watchlist = None
        if self.request.user.is_authenticated:
            if Auction.objects.get(pk = self.kwargs['pk']) in CustomUser.objects.get(id = self.request.user.id).watchlist.all():
                watchlist = True
            else:
                watchlist = None
        return super().get_context_data(**kwargs,
                    category = Auction.objects.get(pk = self.kwargs['pk']).category,
                    watchlist = watchlist)
                                                

class CategoryListView(ListView):
    model = Auction
    template_name = 'marketplace/category.html'
    context_object_name = 'auctions'
    paginate_by = 5

    # Display auctions by category
    def get_context_data(self, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list
        category = self.kwargs['category']
        queryset = queryset.filter(category__name = category)
        form = AuctionFilterForm(self.request.GET)
        queryset = utils.filter_form(form, queryset)
        count = queryset.count()                                

        return super().get_context_data(
                    object_list = queryset,
                    form = form,
                    category = category,
                    count = count,
                    **kwargs)


class WatchlistView(LoginRequiredMixin, ListView):
    model = Auction
    template_name='marketplace/watchlist.html'
    paginate_by = 5
    context_object_name = 'watchlist'

    # Display watchlist    
    def get_context_data(self,  object_list=None, **kwargs):
        user_watchlist = CustomUser.objects.get(id = self.request.user.id).watchlist.all()
        return super().get_context_data(
                    object_list = user_watchlist,
                    count = user_watchlist.count(),
                    **kwargs)
    

    # Adding Auction to watchlist
    def post(self, request):
        user_watchlist = CustomUser.objects.get(id = self.request.user.id).watchlist
        id = self.request.POST.get('id')
        slug = Auction.objects.get(id = id).slug

        if Auction.objects.get(id = id) in user_watchlist.all():
            if self.request.POST.get('remove_watchlist'):
                user_watchlist.remove(id)
        else:
            if self.request.POST.get('add_watchlist'):
                user_watchlist.add(id)

        return redirect('marketplace:auction', id, slug)
    

class MyAuctionsListView(ListView):
    model = Auction
    template_name = 'marketplace/my_auctions.html'
    paginate_by = 5
    context_object_name = 'auctions'

    def get_context_data(self, object_list = None, **kwargs):
        object_list = Auction.objects.filter(created_by = self.request.user.id)

        return super().get_context_data(object_list = object_list, **kwargs)
    

class MyAuctionUpdateView(LoginRequiredMixin, UpdateView):
    model = Auction
    template_name = 'marketplace/update.html'
    context_object_name = 'auction'
    fields = ['name', 'category', 'price', 'photo', 'description']

    def dispatch(self, request, *args, **kwargs):
        # Making sure that only authors can update stories
        obj = self.get_object()
        if obj.created_by != self.request.user:
            return redirect('marketplace:index')
        return super(MyAuctionUpdateView, self).dispatch(request, *args, **kwargs)


class MyAuctionDeleteView(LoginRequiredMixin ,DeleteView):
    model = Auction
    template_name = 'marketplace/delete.html'
    context_object_name = 'auction'
    success_url = reverse_lazy('marketplace:my_auctions')

    def dispatch(self, request, *args, **kwargs):
        # Making sure that only authors can delete stories
        obj = self.get_object()
        if obj.created_by != self.request.user:
            return redirect('marketplace:index')
        return super(MyAuctionDeleteView, self).dispatch(request, *args, **kwargs)

marketplace/templates/marketplace/auction.html
{% extends "marketplace/base.html" %}

{% block title %}
    {{ auction.name }}
{% endblock %}    

{% block content %}
<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 9fr;
    }
    table {
    border-collapse: collapse;
    align-items: center;
    }
    
    tr{
        border-bottom: 1px solid black;     
    }
    td {
        padding: 15px;
    }
</style>
<div class="home-container" >
    <div style="border-right: 1px solid black;">
        Category: <a href="{% url 'marketplace:category' category %}">{{ category }}</a>
        <p>Created by: {{ auction.created_by }}</p>
        <p>{{ auction.date }}</p>

        {% if user.is_authenticated %}
            <form action="{% url 'marketplace:watchlist' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ auction.id }}">

                {% if watchlist %}
                    <input type="hidden" name="remove_watchlist" value="{{ auction.id }}"> 
                    <button>Remove from watchlist</button>
                {% else %}                
                    <input type="hidden" name="add_watchlist" value="{{ auction.id }}"> 
                    <button>Add to watchlist</button>
                {% endif %}

            </form>
        {% endif %}            
    </div>
    <div style="padding-left: 20px;">
        <h2>{{ auction.name }}</h2>
        <h3>{{ auction.price }}$</h3>
        <img src="{{ MEDIA_URL }}{{ auction.photo }}" alt="{{ auction.name }}" style="width: 400px; height: auto;"><br>
        {{ auction.description|linebreaksbr }}
    </div>
</div>    
{% endblock %}

marketplace/templates/marketplace/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
    {% load static %}
    <a href="{% url 'home:index' %}">Apps</a>
    <hr>
    <a href="{% url 'marketplace:index' %}" style="text-decoration:none; color: black;"><h1>🛒 Marketplace</h1></a>
    
    {% if user.is_authenticated %}
        Welcome <a href="{% url 'accounts:index' %}">{{ user.username }}</a>  | 
        <a href="{% url 'accounts:logout' %}?next={{request.path}}">Logout</a>
    {% else %}
        You'are not logged in |         
        <a href="{% url 'accounts:login' %}?next={{request.path}}">Login</a> | 
        <a href="{% url 'accounts:register' %}?next={{request.path}}">Register</a>
    {% endif  %}

    <form action="{% url 'marketplace:index' %}" method="get">
        <input type="search" placeholder="Search" name="q">
        <button>Search</button>
    </form>

    <a href="{% url 'marketplace:index' %}">Home</a> | 

    {% if user.is_authenticated %}
        <a href="{% url 'marketplace:create' %}">Create</a> | 
        <a href="{% url 'marketplace:watchlist' %}">Watchlist</a> |
        <a href="{% url 'marketplace:my_auctions' %}">My Auctions</a>
    {% endif %}
            
    <hr>
    {% block content %}
    {% endblock %}
    <hr>
</body>
</html>

marketplace/templates/marketplace/category.html
{% extends "marketplace/base.html" %}

{% block title %}
    {{ view.category }}
{% endblock %}

{% block content %}
<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 8fr;
    }
    table {
    border-collapse: collapse;
    align-items: center;
    }
    
    tr{
        border-bottom: 1px solid black;     
    }
    td {
        padding: 15px;
    }
</style>
<div class="home-container" >
    <div style="border-right: 1px solid black;">
        <h2>Filters:</h2>

        <form method="get">
            {% for field in form %}
                <p>{{ field.label }}</p>
                <p>{{ field }}</p>
                <hr>
            {% endfor %}                
            <button>Filter</button>
            <br><br> 
        </form>

        <form action="{% url 'marketplace:category' category %}" method="get">
            <button>Clear</button>
        </form>

    </div>
    <div style="padding-left: 20px;">
        {% if count != 1 %}
            <p>{{ count }} auctions found.</p>
        {% else %}
            <p>{{ count }} auction found.</p>
        {% endif %}
                                     
        <table>
            {% for auction in auctions %}
                <tr>
                    <td><p><h3><a href="{{ auction.get_absolute_url }}">{{ auction.name }}</a></h3></p>
                        <img src="{{ MEDIA_URL }}{{ auction.photo }}" alt="{{auction.name}}" style="width: 200px; height: auto;"><br>
                        <p>{{ auction.description|linebreaksbr }}</p>
                        <p>{{ auction.price }}$</p>                    
                    </td>
                </tr>
            {% endfor %}                
        </table>

        {% include "_pagination.html" %}
        
    </div>
</div>
{% endblock %}

marketplace/templates/marketplace/create.html
{% extends "marketplace/base.html" %}
{% block title %}
    Create Auction
{% endblock %}

{% block content %}
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p}}
        <button>Create</button>
    </form>
{% endblock %}

marketplace/templates/marketplace/delete.html
{% extends "marketplace/base.html" %}

{% block title %}
    Delete {{ auction.name }}
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ auction.name }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

marketplace/templates/marketplace/index.html
{% extends "marketplace/base.html" %}

{% block title %}
    Marketplace
{% endblock %}

{% block content %}
<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 9fr;
    }
    table {
    border-collapse: collapse;
    align-items: center;
    }
    
    tr{
        border-bottom: 1px solid black;     
    }
    td {
        padding: 15px;
    }
</style>
<div class="home-container" >
    <div style="border-right: 1px solid black;">

        <h2>Categories:</h2>
        {% for category in categories %}
            <a href="{% url 'marketplace:category' category %}">{{ category }}</a><br>
        {% endfor %}

        <h2>Filters:</h2>
        <form method="get">
            {% for field in form %}
                <p>{{ field.label }}</p>
                <p>{{ field }}</p>
                <hr>
            {% endfor %}                
            <button>Filter</button>
            <br><br> 
        </form>

        <form action="{% url 'marketplace:index' %}" method="get">
            <button>Clear</button>
        </form>            
    </div>
    <div>
        <table>
            {% for auction in auctions %}
                <tr>
                    <td>
                        <p><h3><a href="{{ auction.get_absolute_url }}">{{ auction.name }}</a></h3></p>
                        <p>{{ auction.price }}$</p>
                        <img src="{{ MEDIA_URL }}{{ auction.photo }}" alt="{{auction.name}}" style="width: 200px; height: auto;"><br>
                        <div style="height: 150px; width: 400px;">
                            {{ auction.description|slice:":200"|linebreaksbr }} ...
                        </div>
                                           
                    </td>
                </tr>
            {% endfor %}                
        </table>
        
        {% include "_pagination.html" %}
    </div>

</div>
    
{% endblock %}

marketplace/templates/marketplace/my_auctions.html
{% extends "marketplace/base.html" %}

{% block title %}
    My Auctions
{% endblock %}

{% block content %}
<style>
    table {
    border-collapse: collapse;
    align-items: center;
    }
    
    tr{
        border-bottom: 1px solid black;     
    }
    td {
        padding: 15px;
    }
</style>
<table>
    {% for auction in auctions %}
        <tr>
            <td>
                <p>
                    <h3><a href="{{ auction.get_absolute_url }}">{{ auction.name }}</a></h3>
                    <a href="{% url 'marketplace:update' auction.id %}">Update</a> |
                    <a href="{% url 'marketplace:delete' auction.id %}">Delete</a> 
                </p>
                <p>{{ auction.price }}$</p>
                <img src="{{ MEDIA_URL }}{{ auction.photo }}" alt="{{auction.name}}" style="width: 200px; height: auto;"><br>
                <div style="height: 150px; width: 400px;">
                    {{ auction.description|slice:":200"|linebreaksbr }} ...
                </div>
                                   
            </td>
        </tr>
    {% endfor %}                
</table>
{% include "_pagination.html" %}
{% endblock %}

marketplace/templates/marketplace/update.html
{% extends "marketplace/base.html" %}

{% block title %}
    Delete {{ auction.name }}
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

marketplace/templates/marketplace/watchlist.html
{% extends "marketplace/base.html" %}

{% block title %}
    Watchlist
{% endblock %}

{% block content %}
    {% if count != 1 %}
        {{ count }} auctions in watchlist.
    {% else %}
        {{ count }} auction in watchlist.
    {% endif %}
    
    <table>
        {% for auction in watchlist %}
            <tr>
                <td><p><h3><a href="{{ auction.get_absolute_url }}">{{ auction.name }}</a></h3></p>
                    <img src="{{ MEDIA_URL }}{{ auction.photo }}" alt="{{auction.name}}" style="width: 200px; height: auto;"><br>                   
                </td>
            </tr>
        {% endfor %}                
    </table>
    {% include "_pagination.html" %}
{% endblock %}